


--  POSTGRESQL



CREATE TABLE reprogramaciones.usuario (
	id SERIAL PRIMARY KEY,
	nombres VARCHAR(100),
    apellidos VARCHAR(100),
    correo VARCHAR(100),
    perfil VARCHAR(50),
    programa VARCHAR(100),
	activo BOOLEAN,
	usuario_responsable VARCHAR(50));
CREATE TABLE reprogramaciones.configuracion (
    id SERIAL PRIMARY KEY,
    limite INTEGER,
    plazo INTEGER,
    cdocente BOOLEAN,
    calumno BOOLEAN,
    cdoa BOOLEAN,
    ccoordinador_programa BOOLEAN,
    ccoordinador_ambiente BOOLEAN);



INSERT INTO reprogramaciones.usuario 
    (nombres, apellidos, perfil, correo, programa, activo, usuario_responsable)
VALUES 
    ('Carlos Eduardo', 'Ramírez Soto', 'DOA', 'carlos.ramirez@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Lucía Fernanda', 'Pérez Ríos', 'DOA', 'lucia.perez@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('María José', 'Delgado León', 'DOA', 'maria.delgado@upsjb.edu.pe', '', false, 'nombre.apellido@upsjb.edu.pe'),
    ('Javier Antonio', 'Gómez Vidal', 'DOA', 'javier.gomez@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Ana Isabel', 'Torres Cárdenas', 'DOA', 'ana.torres@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Diego Martín', 'Reyes Camargo', 'DOA', 'diego.reyes@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Valeria Sofía', 'Morales Luna', 'DOA', 'valeria.morales@upsjb.edu.pe', '', false, 'nombre.apellido@upsjb.edu.pe'),
    ('Luis Alberto', 'Salazar Huamán', 'DOA', 'luis.salazar@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Camila Andrea', 'Rojas Paredes', 'DOA', 'camila.rojas@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Fernando José', 'Quispe Vargas', 'DOA', 'fernando.quispe@upsjb.edu.pe', '', false, 'nombre.apellido@upsjb.edu.pe'),
    ('Isabela Ruth', 'Carranza Díaz', 'DOA', 'isabela.carranza@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Andrés Felipe', 'Mejía Ortiz', 'DOA', 'andres.mejia@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Patricia Elena', 'López Medina', 'DOA', 'patricia.lopez@upsjb.edu.pe', '', false, 'nombre.apellido@upsjb.edu.pe'),
    ('Esteban Gabriel', 'Sánchez Bravo', 'DOA', 'esteban.sanchez@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Daniela Ivonne', 'Vargas Espinoza', 'DOA', 'daniela.vargas@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Rodrigo Manuel', 'Cáceres Pinto', 'DOA', 'rodrigo.caceres@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Karina Fabiola', 'Gutiérrez Zegarra', 'DOA', 'karina.gutierrez@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Julio César', 'Navarro Rivas', 'DOA', 'julio.navarro@upsjb.edu.pe', '', false, 'nombre.apellido@upsjb.edu.pe'),
    ('Gabriela Antonia', 'Silva Aguirre', 'DOA', 'gabriela.silva@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe'),
    ('Álvaro Ignacio', 'Castro Aliaga', 'DOA', 'alvaro.castro@upsjb.edu.pe', '', true, 'nombre.apellido@upsjb.edu.pe');



INSERT INTO reprogramaciones.configuracion
    (limite, plazo, cdocente, calumno, cdoa, ccoordinador_programa, ccoordinador_ambiente)
VALUES 
    (3, 5, true, true, true, true, true);



SELECT * FROM reprogramaciones.usuario;
SELECT * FROM reprogramaciones.configuracion;


DROP TABLE reprogramaciones.usuario;
DROP TABLE reprogramaciones.configuracion;
DROP SCHEMA reprogramaciones CASCADE;



--  ORACLE



CREATE TABLE IDO_REPROGRAMACION_CLASES.USUARIO (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR2(100),
    apellidos VARCHAR2(100),
    correo VARCHAR2(100),
    perfil VARCHAR2(50),
    programa VARCHAR2(100),
    activo CHAR(1) CHECK (activo IN ('Y','N')),
    usuario_responsable VARCHAR2(50));
CREATE TABLE IDO_REPROGRAMACION_CLASES.CONFIGURACION (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limite INTEGER,
    plazo INTEGER,
    cdocente CHAR(1) CHECK (cdocente IN ('Y','N')),
    calumno CHAR(1) CHECK (calumno IN ('Y','N')),
    cdoa CHAR(1) CHECK (cdoa IN ('Y','N')),
    ccoordinador_programa CHAR(1) CHECK (ccoordinador_programa IN ('Y','N')),
    ccoordinador_ambiente CHAR(1) CHECK (ccoordinador_ambiente IN ('Y','N')));



INSERT INTO IDO_REPROGRAMACION_CLASES.USUARIO
    (nombres, apellidos, correo, perfil, programa, activo, usuario_responsable)
VALUES
    ('Aaron', 'Mori Valdivia', 'christian.mori@upsjb.edu.pe', 'DOA', '', 'Y', 'aaron-mv@outlook.com');

INSERT INTO IDO_REPROGRAMACION_CLASES.CONFIGURACION
    (limite, plazo, cdocente, calumno, cdoa, ccoordinador_programa, ccoordinador_ambiente)
VALUES
    (3, 5, 'Y', 'Y', 'Y', 'Y', 'Y');



SELECT * FROM IDO_REPROGRAMACION_CLASES.USUARIO;
SELECT * FROM IDO_REPROGRAMACION_CLASES.CONFIGURACION;
